### ISSUE TITLE
Member kann nicht gelöscht werden, wenn buch ausgeliehen

### ISSUE THREAD

**Issue by mariluchs** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#117]

**Comment by VTPDE0** [comment]
Fertig und getestet, aber vor dem Abschluss müssen wir mit der Gruppe besprechen, ob der Frontend-Teil benötigt wird. Der Code befindet sich derzeit nur lokal auf meinem Computer.

**Comment by mariluchs** [comment]
Backend funktioniert, Frontend fehlt, wird bis Vortrag nicht bearbeitet
