### ISSUE TITLE
Der Mitarbeiter kann den Vornamen des Kunden einsehen/ändern/anlegen

### ISSUE THREAD

**Issue by AngeloVienibene** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#12]
Erstellung eines Textfeldes, das den Vornamen des Benutzers speichert.

**Comment by Jules2543** [comment]
Ist es wirklich notwendig den Vornamen ändern zu können?

**Comment by VTPDE0** [comment]
mit der Einführung von memberlist und member_details ist Name und Vorname Änderungen sind implementiert
