### ISSUE TITLE
Alle Verknüpfungen (Links) auf alle Member Seiten anpassen

### ISSUE THREAD

**Issue by VTPDE0** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#130]
- [ ] alle Anforderungen aus dem Issue wurden umgesetzt
- [ ] Code wurde von Entwickler getestet
- [ ] Test in Kommentar dokumentieren
- [ ] Absprache mit betroffenen Teammitgliedern

**Comment by AngeloVienibene** [comment]
Alle Verknüpfungen und Links auf allen Memberseiten wurden angepasst.
