### ISSUE TITLE
Alle Kommentare auf Englisch übersetzen

### ISSUE THREAD

**Issue by VTPDE0** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#142]
- [ ] alle Anforderungen aus dem Issue wurden umgesetzt
- [ ] Code wurde von Entwickler getestet
- [ ] Test in Kommentar dokumentieren
- [ ] Absprache mit betroffenen Teammitgliedern

**Comment by FlobiusKane** [comment]
Siehe Issue Englische Kommentare prüfen #79
