### ISSUE TITLE
Unnötige/Nicht brauchbare Files im Frontend Ordner löschen

### ISSUE THREAD

**Issue by Jules2543** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#146]
Unnötige/Nicht brauchbare Files , wie beispielsweise Test-Files, im Frontend Ordner löschen

**Comment by Jules2543** [comment]
@FlobiusKane @AngeloVienibene bitte nachschauen ob alle unnötigen Files von euch auch gelöscht wurden.

**Comment by Jules2543** [comment]
@AngeloVienibene es gibt zwei Dashboard Seiten.

**Comment by FlobiusKane** [comment]
brauchen wir das template background file überhaupt noch? ich glaub das kann auch weg
