### ISSUE TITLE
Dahboard besprechen und ggf. überarbeiten

### ISSUE THREAD

**Issue by Jules2543** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#147]
Dashboard Layout, braucht man die Suchleiste Search Books?
Das Dashboard ist nicht an unterschiedliche Auflösungen angepasst.

**Comment by FlobiusKane** [comment]
Suchleiste kann da glaub weg, da sollten wir vielleicht auch mal bei den anderen seiten schauen ob man bei denen die suchleiste überhaupt braucht bzw. ich glaub die suchleiste funktioniert auch nur bei der bookliste d.h. man müsste wenn man die woanders verwendet dementsprechend die links anpassen

**Comment by AngeloVienibene** [comment]
Letzte Bearbeitungen am Dashboard wurden durchgeführt.
