### ISSUE TITLE
Alle Javaskript Funktionen in das Javaskript File einfügen

### ISSUE THREAD

**Issue by Jules2543** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#150]

**Comment by Jules2543** [comment]
In Booklist ist noch Javaskript Code enthalten, mit @mariluchs besprechen und entsprechend die Seite dann bearbeiten.

**Comment by FlobiusKane** [comment]
Ich hab meinen ganzen javascript code in die js datei eingefügt. in den Member files ist auch noch java code drin den hab ich aber nicht angefasst weil ich nicht weiß was der macht

**Comment by AngeloVienibene** [comment]
Ich habe aus der Memberlist Seite das letzte js script entfernt und es in da script.js eingefügt.
