### ISSUE TITLE
User kann Telefonnummer eines Mitglieds anlegen

### ISSUE THREAD

**Issue by AngeloVienibene** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#18]
Erstellung eines Textfeldes, das die Telefonnummer des Benutzers speichert.

**Comment by Jules2543** [comment]
Ja guter Punkt, dann würde ich den Punkt Telefonnummer auch im Bereich Benutzerkonto anlegen, hinzufügen. Die Frage ist nur als Pflichtfeld oder nicht?
