### ISSUE TITLE
User kann Zahlungsverbindung anlegen

### ISSUE THREAD

**Issue by AngeloVienibene** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#19]
Der User kann die Zahlungsverbindung eines Mitglieds anlegen.

**Comment by Jules2543** [comment]
Nehmen wir das mit rein, oder wird das zu komplex?

**Comment by mariluchs** [comment]
Extra Feature, wird gemacht wenn genug Zeit da ist.
