### ISSUE TITLE
Im Benutzerkonto gibt es ein Feld für das Beitrittsdatum

### ISSUE THREAD

**Issue by AngeloVienibene** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#20]
Erstellung eines Datumsfeld, das das Beitrittsdatum des Benutzers speichert.
Es muss ein Datumsfeld gegeben sein, dass das Beitrittsdatum des Benutzers aufnimmt.

**Comment by Jules2543** [comment]
Gibt es dann auch ein Datum, über das Austrittsdatum?
