### ISSUE TITLE
Ein Buch kann ausgeliehen werden

### ISSUE THREAD

**Issue by AngeloVienibene** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#21]
Die Software muss die Möglichkeit bieten, Bücher aus der Bibliothek auszuleihen.
Die Nutzer müssen die Möglichkeit haben, Bücher aus der Bibliothek auszuleihen

**Comment by TOBI526** [comment]
BE steht, FE muss evtl noch Texte anpassen.
