### ISSUE TITLE
Der User kann neue Member anlegen

### ISSUE THREAD

**Issue by mariluchs** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#24]
Ein neuer Benutzer wird angelegt. 
Verpflichtende Felder: 
member_id, name, vorname, email, address, phone_number

**Comment by Jules2543** [comment]
Mehr verpflichtende Felder müssen hinzugefügt werden: Name, Nachname, Geburtsdatum, Adresse, E-Mail, Kundennummer, Bankverbindung
