### ISSUE TITLE
Der User kann dem Bestand neue Bücher hinzufügen

### ISSUE THREAD

**Issue by mariluchs** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#25]
Ein neues Buch wird dem Bestand hinzugefügt. 
Verpflichtende Daten:
book_id, title, author, genre, ISBN, available_copies

**Comment by Jules2543** [comment]
Mehr verpflichtende Felder müssen hinzugefügt werden: Titel, Autor, ISB, Genre, Auflage, Verfügbarkeit/Bestand,ID, Status

**Comment by Jules2543** [comment]
Bei Issue #10 steht, dass der Mitarbeiter die Seitenzahl anlegen/einsehen kann. Dann müssen wir diese hier noch mit dazu nehmen

**Comment by Jules2543** [comment]
Könnten wir nicht ein neues Issue hinzufügen, mit allen Punkten, die der Mitarbeiter bei einem Buch einsehen und anlegen kann? #10 #9 #8 #7 #6
