### ISSUE TITLE
Wir legen ein allgemeines Framework als Basis fest

### ISSUE THREAD

**Issue by FlorianLichtenberger** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#29]
Basierend auf den Anforderung des Systems bietet sich die Verwendung eines Web Development Frameworks an.

Dabei könnte dann bspw. auf die Programmiersprachen Express.js (Basiert auf Node.js; Also JavaScript) oder Python oder Ruby zurückgegriffen werden

**Comment by TOBI526** [comment]
Dieses Issue wird mit den Issues #30 und #31 bearbeitet. Das Issue wird geschlossen.
