### ISSUE TITLE
Layout des Bücherkatalogs festlegen

### ISSUE THREAD

**Issue by Jules2543** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#33]
Idee 1: 
Name des Buches mit Bild untereinander
![Screenshot 2024-04-14 124311](https://github.com/IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek/assets/166832919/6ce19461-7bae-4232-b844-79bd970ecab8)

Idee 2:
Nebeneinander mit Titel und Bild in Bsp. 3 Spalten
![image](https://github.com/IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek/assets/166832919/a4dd4c95-caca-4593-8f20-eb9cde3f113b)

Idee 3:
Nur als Auflistung untereinander mit Name und rechts ganz kleines Bild
![image](https://github.com/IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek/assets/166832919/74381c80-ff95-4488-acde-4c1a775c89b3)

oder: Idee 4:
Eine (Spalten) Ansicht von Titel mit Bild, die man mit einem Button rechts oben umstellen kann. Und die Bücher dann anders angezeigt werden, untereinander aufgelistet wie in Idee 3.

**Comment by mariluchs** [comment]
Tabellenform
