### ISSUE TITLE
Bibliothekswebanwendung benennen

### ISSUE THREAD

**Issue by Jules2543** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#34]
LibrioFact

**Comment by mariluchs** [comment]
Vorschlag: 
- **Libriofact**: Eine Verknüpfung aus "librio" (Bücher) und "facilis" (einfach) auf Lateinisch.
- **OpenLMS**: Könnte für Open Source Library Management Software stehen
