### ISSUE TITLE
FrontEnd-Prototyp erstellen

### ISSUE THREAD

**Issue by mariluchs** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#42]
Das Frontend Team erstellt einen Protoyp um zu zeigen, wie die verschiedenen Seiten aussehen könnten und wie der User mit der Anwendung interargiert.

**Comment by FlorianLichtenberger** [comment]
<img width="523" alt="image" src="https://github.com/IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek/assets/166111980/495e454d-7bdf-4e75-ada6-e548f28ff0a3">

**Comment by FlorianLichtenberger** [comment]
Storyboard stand 19.04.24

**Comment by FlorianLichtenberger** [comment]
<img width="680" alt="image" src="https://github.com/IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek/assets/166111980/4bf2d088-ebdc-4635-9498-a2fc7b56d389">

**Comment by FlorianLichtenberger** [comment]
Prototyp Bibliothek Design Frontend
Stand: 28.04.2024

**Comment by FlorianLichtenberger** [comment]
https://www.figma.com/file/y0iqTiMoVKlHZxD6dGu1wl/Prototyp-Design-Bibliothek?type=design&node-id=43%3A1088&mode=design&t=CjFXSJ2Vv1DjS8t6-1

**Comment by FlorianLichtenberger** [comment]
Link zum Figma Design

**Comment by FlorianLichtenberger** [comment]
![image](https://github.com/IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek/assets/166111980/9d79dd8d-464d-4485-ab83-58936ac96fc6)

**Comment by FlorianLichtenberger** [comment]
Update stand 30.04
