### ISSUE TITLE
Datenbankstruktur skizzieren

### ISSUE THREAD

**Issue by mariluchs** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#43]
Das Backendteam skizziert die Datenbankstruktur.

**Comment by mariluchs** [comment]
[Entity Relation Diagram](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Kopie%20von%20LMS%20-%20Entity%20Relationship%20Diagramm.drawio.png#R7V1tc5s4EP41%2FpgMgoDtj7WT9DJNMpmkvet96pCg2Ewx8oEcO%2F31J4EE2LIdFJs3S21nioQQsPtoH1YrrXvWeLb6Grnz6R3yYNAzDW%2FVsy57pmkODUD%2BozXvaQ0A1kVaM4l8j9XlFU%2F%2BH8gqDVa78D0YrzXECAXYn69XvqAwhC94rc6NIrRcb%2FaKgvW7zt0JFCqeXtxArP3H9%2FA0rR2Y%2Fbz%2BL%2BhPpvzOwBmmZ2Yub8zeJJ66HloWqqyrnjWOEMLp0Ww1hgGVHpdLet31jrPZg0UwxGUuuL21Jubqx9vf95ffHq5ub%2B7xzfUZ6%2BXNDRbshUcI%2FWYPjN%2B5FMizz%2Bkhdp9p1SjGboSZsiyDVBDxY9cPYUQqQFIOAnce%2B0nztGbqB96t%2B44WmHfES6NXfwW9x1RXtC1R2y3pjBZp56%2Bk8yf2MPS0G%2FiTkBy%2FkDendxxFMCbPcuvGmLWY4lnADkUx8XeGEYarQhUT21eIZhBH76QJh3GfqZCB2HRYeZkjAgxY3bSIBptVugyFk6zvXFHkgOlKQm%2BmoLf9OnukyBtNUeT%2FoZoKmGSLekzKS38WuCGBtOttVI1QMoYNQbm0xovQ%2FLsbTSBmFXPkhzh5aXtE%2FhExjI1zu2eTBxuTMsjL5B9tHuExCmMcERDRPiDR5RJSfY4wmrNOA%2FjK%2B4%2BYkOnxM8IYzXaqey%2FuP8YA07lVUuVWVRq3BI0%2FfNupc%2FL%2B2HeDR2IR3XCSDFlmIN1caVsFmwlzU8qbgxAR2b0GiUGb%2Bp4HyYAcLac%2Bhk9z94U2WhJG%2BGgo7sX2x7opKMOS1AXrLJeQdG9uQIxP6GIyMhahFwsKzp7z8zq%2F2Gqdf91c1ql4bm3TtqOYqNcPJ7fplc4GMuyWIGO1e9TaR0VKqe5qgIqtCUEkBKNCQij7DVAZITjlNV6BVYCezy%2Bulg3s0oo5dTboCwr%2F7mP6rC3igjbgQDnbD0QvThv%2FSo3%2FsGnjDyQcwC5bf1BeNadu%2FoHoAd48je4VMf8SQFDO%2FpvGQBNAvQQAzKYZwDSGalBAjm7NAVlYpKD0J%2BziRawIDciAQTkeGIjguIOzZxjtJ4OeavGcs2zyhs%2Fl2CWteXUBnYH24Q6L6GTg705IZyA6caca0xloPy4ThejHpVZa3biOBDrUI3UxCKiJQca3kyeGxkM7A4loXpdduwzbmhUGYjjvDZF7zlSJ70hgQT0OEEN%2FmgOq5YDGIzwDiTndTnNAv7RqTp4DxBldlQigPBCUIwBujTQB1EYAzUd4hhJTgl1mgGF53Zw6AwzFGUE4c%2F1AEQqQQIJyFAAM0UMcIbrDaT8T9DoV3dmGIxE80uH6i4uyAZ5BVdYcGNqJ28Hhn1gNlA2G7kR7wJZVOu0L90iPxQ%2FALsXpzlEtd5neajHcolv3nBjuX%2BS6NhF7mYBP%2FfhYrWuzOH7N4zJ9me5qWc6tvb0dawFqYYrGwz9gy4L%2B62%2FgRKkCfMr9O02q2Lqs3wnoQPH8N3I4wYnW0O%2BEO9Iz5FaFk6oyigSMFGQUcc2JZpT6fI%2FGg0kAiKtIrmv1PUrMJh7LEFil1XP6fLJtIYnAJ7N0%2BVknGKUdwFGQQSS2m2sGOTqDNB%2BNAkBi%2FrLbBFJeO6dPIOKc5TMLOjjujEo1fI5T4RoeeRRluKI8RtTjCm4YNFc0wxVldzNVmJ1Awt%2FsNFdkUNdcAUzRx4wgXkShYtwggQkFuUH0SL8sMDH9%2Bxmi16lVDCJSPrFHlSlHMigxrM6maw%2FwwJyjZvkcVq1ZtGCKXl%2F7Fi0cKcWM%2BSnH7yQXIgJTdPxSO63uLlUZfKi3PNGUSEejDj0YldJD8ysVeM%2FtdfSONfaHpZVz8txgictT7tXZpyQDBfVowBEnAb7CMNoNDjXdO3vjJyXKTtlV5945OoP4ge6dU34He2vcO0d06k%2FWvXN0KvFcFqJbn5hphb07CXgoSOs6w%2ByB3p08OzTv3TkSPn2nvTtHp5jNZMG%2FTDepQaFUFDJ4UI8L%2BuK3w49YJ5ndAMSFte7hOWUXgVeXYxb0NYsf6OP1y%2B9bbI2P1xdZ%2FGR9vL4m8kwWW9KBUzutsIsngQ71aF1nID%2FUxZMnh%2BZdvC05yOu0DvW5eDoDeUEW4vJclQJ4Ot34PuHofOO100Dz%2B4NVyTgOdMrxgizE4N%2F9Av%2BBLO14uheYWOZwDQfOfwuEuULO4lQjX6jwI5gogjfI9w%2BT%2B1jD9IjvL067zRrUdytFKE5nU98jHJ2Jr3aKa8EGZlUyqgOdUr0giy2Tn24cL8mQUYYLdGL13cLZkln9aoVhGPso3E8KvU5FtBBFHKbGeJD05QfBGAUoSl7MerXpX3aPQn36J3nTCP2GhTNO8mcrCuX3ulmcCLKYSfOxMpns6%2Bp8JICKsfPBIO1Q1G1LKvfORd0a0LSepc1lIc7SQk5NXUwd3GWwKfhhpOeBdzjJXeC%2F5gOLQ3FGuXUZJ9tnkfTsdC4LcXa6nWnzTw1ZCnKdnhDuMNc1Hz0ddn1muQE16znqXBbiHHXu6HUic1qX4aUc3Zl8dlXTXRfprvlIqml0%2FZdJa9dzPuY035mGODWuGa5CQCnIcCXyD0NvAvmUNZG1j98fYeBi8s11lZ9JJ7ZTigPmus5h6H1JUqFbl1ePKITf0Z0bvlOw0ReDnAJJ39H7z2LhX1o4t3nxclU8ecl5Eq58%2FJPfihwXriKl%2FCJa4NeI4OG%2FGoYW0QvcR0Q8uR3mRLxTuGk7Kr6yZgwYW3CRVUaJ2N%2Fg2gPvAd8D%2FTrIYQ34b7vy33rd%2FAnX9N3ZVTnYhI7MjY6szY5S0QgdHQ%2B1JRbh1oZahj5DAn0Z0oEc0g9ALU%2Fa0TnUZmaRo9b5JGqtjY6szY4qR22JvMC129oz49ww7CIMSQ2wrY9sLi09wMgnUkkW8awZ4nPD7K8NB8Me7B8QpLDZ2wFg5z9x9yHY%2Be9Htgbt2YfBoWg37abRXmKquG4bXc8XwuBkQXUG1juyN1eVfRpUpBghukMhb05ch%2Bkd8iBt8T8%3D)

**Comment by TOBI526** [comment]
Version 2: https://app.diagrams.net/?client=1#HIU-Internationale-Hochschule-Augsburg%2FFallstudie-Bibliothek%2Fmain%2FUnbenanntes%20Diagramm.drawio#%7B%22pageId%22%3A%22r055tTo90BwaU_G7bR6q%22%7D
