### ISSUE TITLE
Es gibt verschiedene Aktivitäten für ein Buch

### ISSUE THREAD

**Issue by mariluchs** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#5]
- Ausleihen
- Zurückgeben
- Vorbestellen

**Comment by Jules2543** [comment]
Ja das stimmt. Könnten wir nicht ein neues Issue für jeden Vorgang machen?

- Ausleihprozess verwalten (Auswahl des Benutzers, Einscannen der Bücher-ID, Zeit)
- Rückgabeprozess verwalten (Einscannen der Bücher-ID, Status, Mahnung)
- Reservierungssystem verwalten (Vorab Reservierung, Status)
- Verlängerungsprozess verwalten (Zeit, Status)
- Vorbestellung verwalten (Name des Buches, Anzahl der Bücher)
