### ISSUE TITLE
Englische Kommentare prüfen

### ISSUE THREAD

**Issue by Jules2543** [IU-Internationale-Hochschule-Augsburg/Fallstudie-Bibliothek#79]
Prüfen ob alle Kommentare auf Englisch sind.

**Comment by Jules2543** [comment]
@AngeloVienibene bei deinem css Code fehlen Kommentare

**Comment by Jules2543** [comment]
Bookseiten habe ich mir angeschaut, da passen die Kommentare. Beim Javaskript und css File ebenfalls. (Abgesehen, dass deine fehlen @AngeloVienibene)

Wenn ihr im css oder Javakript File weitere hinzufügt, bitte als Kommentar hier reinschreiben!

**Comment by FlobiusKane** [comment]
Files bei denen die kommentare noch auf deutsch sind: add member, (dashboard old, aber das kann auch eigentlich gelöscht werden oder @AngeloVienibene), member details

**Comment by AngeloVienibene** [comment]
Meinen Seiten ( add member und dem dashboard) wurden die nötigen Kommentare auf Englisch angefügt.
